/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ["./app/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        'primary-100': 'var(--color-primary-100)',
        'primary-200': 'var(--color-primary-200)',
        'primary-300': 'var(--color-primary-300)',
        'primary-400': 'var(--color-primary-400)',
        'primary-500': 'var(--color-primary-500)',
        'primary-600': 'var(--color-primary-600)',
        'primary-700': 'var(--color-primary-700)',
        'secondary-100': 'var(--color-secondary-100)',
        'secondary-200': 'var(--color-secondary-200)',
        'secondary-300': 'var(--color-secondary-300)',
        'secondary-400': 'var(--color-secondary-400)',
        'secondary-500': 'var(--color-secondary-500)',
        'secondary-600': 'var(--color-secondary-600)',
        'secondary-700': 'var(--color-secondary-700)',
        'tertiary-50': 'var(--color-tertiary-50)',
        'tertiary-100': 'var(--color-tertiary-100)',
        'tertiary-200': 'var(--color-tertiary-200)',
        'tertiary-300': 'var(--color-tertiary-300)',
        'tertiary-400': 'var(--color-tertiary-400)',
        'tertiary-500': 'var(--color-tertiary-500)',
        'tertiary-600': 'var(--color-tertiary-600)',
        'tertiary-700': 'var(--color-tertiary-700)',
        'neutral-50': 'var(--color-neutral-50)',
        'neutral-100': 'var(--color-neutral-100)',
        'neutral-150': 'var(--color-neutral-150)',
        'neutral-200': 'var(--color-neutral-200)',
        'neutral-300': 'var(--color-neutral-300)',
        'neutral-400': 'var(--color-neutral-400)',
        'neutral-500': 'var(--color-neutral-500)',
        'neutral-600': 'var(--color-neutral-600)',
        'neutral-700': 'var(--color-neutral-700)',
        'neutral-800': 'var(--color-neutral-800)',
        'neutral-900': 'var(--color-neutral-900)',
        'green-100': 'var(--color-green-100)',
        'green-200': 'var(--color-green-200)',
        'green-300': 'var(--color-green-300)',
        'green-400': 'var(--color-green-400)',
        'green-500': 'var(--color-green-500)',
        'green-600': 'var(--color-green-600)',
        'green-700': 'var(--color-green-700)',
        'red-100': 'var(--color-red-100)',
        'red-200': 'var(--color-red-200)',
        'red-300': 'var(--color-red-300)',
        'red-400': 'var(--color-red-400)',
        'red-500': 'var(--color-red-500)',
        'red-600': 'var(--color-red-600)',
        'red-700': 'var(--color-red-700)',
        white: 'var(--color-white)',
        black: 'var(--color-black)',
        silver: 'var(--color-silver)',
        background: 'var(--color-background)'
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/line-clamp'),
  ],
}